service: sajjad-device-handler

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: eu-north-1
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/sajjad_devices"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  app:
    handler: wsgi_handler.handler
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

custom:
  wsgi:
    app: python_code_challenge.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!.env'
    - '!.git/**'
    - '!.github/**'
    - '!.serverless/**'
    - '!static/**'
    - '!.cache/**'
    - '!.pytest_cache/**'
    - '!node_modules/**'
    - '!__pychache__'

resources:
  Resources:
    devicesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sajjad_devices
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

